---
abstract: 'Utility routines for vec strings.'
author:
  - 'Vincent Pit <perl@profvince.com>'
build_requires:
  Carp: 0
  Config: 0
  Exporter: 0
  ExtUtils::MakeMaker: 0
  Test::More: 0
  XSLoader: 0
  base: 0
configure_requires:
  Config: 0
  ExtUtils::MakeMaker: 0
  File::Spec: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Scalar-Vec-Util
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 0
  Exporter: 0
  XSLoader: 0
  base: 0
  perl: 5.006
resources:
  bugtracker: http://rt.cpan.org/NoAuth/ReportBug.html?Queue=Scalar-Vec-Util
  homepage: http://search.cpan.org/dist/Scalar-Vec-Util/
  license: http://dev.perl.org/licenses/
  repository: http://git.profvince.com/?p=perl%2Fmodules%2FScalar-Vec-Util.git
version: 0.07
